
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crafty_news_API_tech_interview_development
  username: postgres

test:
  <<: *default
  database: crafty_news_API_tech_interview_test
  username: postgres

production:
  <<: *default
  database: crafty_news_API_tech_interview_production
  username: crafty_news_API_tech_interview
  password: <%= ENV['CRAFTY_NEWS_API_TECH_INTERVIEW_DATABASE_PASSWORD'] %>
